const resorts = [
  {
    _id: "1",
    name: "Lakawon Island Resort",
    price_per_night: 2804.0,
    description:
      "On a lush 16-hectare island with white-sand beaches, this relaxed resort is 5 km from the jetty in Cadiz Viejo, a village on the mainland.",
    address: "Cadiz Viejo",
    city: "Cadiz",
    province: "Negros Occidental",
    zip_code: "6121",
    latitude: 11.045411,
    longitude: 123.201465,
    contact_number: "(034) 213 6354",
    website: null,
    amenities: ["Pool", "Breakfast", "Parking", "Beach access"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "2",
    name: "Bluewater Maribago Beach Resort",
    price_per_night: 4156,
    description:
      "Set in a complex of thatch-roofed buildings on the Cebu Strait, this posh beachfront resort is 1 km from Mactan Island Aquarium and 4 km from the Magellan Shrine.",
    address: "Buyong",
    city: "Lapu-Lapu",
    province: "Maribago Mactan Island",
    zip_code: "6015",
    latitude: 10.290899,
    longitude: 124.000822,
    contact_number: "(032) 402 4100",
    website: "http://www.bluewater.com.ph/",
    amenities: ["Pool", "Spa", "Parking", "Wi-Fi"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "3",
    name: "Camayan Beach Resort",
    price_per_night: 9316,
    description:
      "Set in a complex of thatch-roofed buildings on the Cebu Strait, this posh beachfront resort is 1 km from Mactan Island Aquarium and 4 km from the Magellan Shrine.",
    address: "Ilanin Road",
    city: "Subic Bay Freeport Zone",
    province: "Bataan",
    zip_code: "2222",
    latitude: 14.7647213,
    longitude: 120.250671,
    contact_number: "(047) 252 8000",
    website: "https://www.camayanbeachresort.ph/",
    amenities: ["Pool", "Spa", "Parking", "Breakfast"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "4",
    name: "Sabang Inn Beach Resort",
    price_per_night: 1195,
    description:
      "Flanked by palm trees, this relaxed hotel on Sabang Beach is 2 minutes on foot from Sabang ferry terminal, 12 km from the Malasimbo Amphitheater and 18 km from Tamaraw Falls.",
    address: "Sabang Beach",
    city: "Puerto Galera",
    province: "Oriental Mindoro",
    zip_code: "5203",
    latitude: 13.522548,
    longitude: 120.977825,
    contact_number: "(043) 287 3198",
    website: "http://www.sabanginn.com/",
    amenities: ["Pool", "Parking", "Beach access", "Air conditioning"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "5",
    name: "Playa Tropical Resort Hotel",
    price_per_night: 2479,
    description:
      "Set 11 km from the Baroque Paoay Church, this traditional Balinese-inspired beachfront resort is 17 km from the scenic Paoay Sand Dunes.",
    address: "Barangay Victoria Currimao",
    city: "Laoag",
    province: "Ilocos Norte",
    zip_code: "2900",
    latitude: 17.997242,
    longitude: 120.498991,
    contact_number: "(077) 670 1211",
    website: "https://playatropical.ph/",
    amenities: ["Pool", "Spa", "Parking", "Breakfast"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "6",
    name: "Utopia Resort & Spa",
    price_per_night: 2799,
    description:
      "Utopia Resort & Spa; a luxury resort in the Philippines. Join us at our five star resort in Puerto Galera! Utopia Resort & Spa is perched on top of the hill at Palangan, the first Barangay on the peninsular of Puerto Galera.",
    address: "Palangan Rd",
    city: "Puerto Galera",
    province: "Oriental Mindoro",
    zip_code: "5203",
    latitude: 13.503291,
    longitude: 120.962143,
    contact_number: "(043) 287 3681",
    website: "https://utopiaresort.ph/",
    amenities: ["Pool", "Breakfast", "Wi-Fi", "Parking"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "7",
    name: "Duli Beach Resort",
    price_per_night: 1635,
    description:
      "Set on Duli Beach overlooking Base Bay, this unfussy resort surrounded by palm trees is 4 km from Verde Safari Beach and 7 km from Makinit Hot Springs.",
    address: "Barangay Bucana",
    city: "El Nido",
    province: "Palawan",
    zip_code: "5313",
    latitude: 11.348115,
    longitude: 119.456259,
    contact_number: null,
    website: "https://www.dulibeach.com/",
    amenities: ["Parking", "Beach access", "Air conditioning", "Restaurant"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "8",
    name: "Whispering Palms Island Resort",
    price_per_night: 1494,
    description:
      "At our resort going traditional charm and uniqueness of Philippine culture hand in hand. In an idyllic bay with turquoise-tropical water provides the Whispering Palms Bungalow Resort on Sipaway Island our discerning travelers the amenities of a comfortable life, and at the same time easy access to numerous Activities.",
    address: "Sipaway Island",
    city: "San Carlos",
    province: "Negros Occidental",
    zip_code: "6127",
    latitude: 10.472718,
    longitude: 123.449032,
    contact_number: "0917 310 6246",
    website: "https://whispering-palms.com/",
    amenities: ["Pool", "Parking", "Beach access", "Air conditioning"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "9",
    name: "Hoyohoy Villas",
    price_per_night: 2176,
    description:
      "Set on a serene, sandy beach along the Philippine Sea, this relaxed resort surrounded by palm trees is a 5-minute walk from Sta. Fe ferry terminal and 26 km from the remnants of a Spanish fort at Kota Park.",
    address: "Bantayan Island,F. Roska Street",
    city: "Santa Fe",
    province: "Cebu",
    zip_code: "6047",
    latitude: 11.162276,
    longitude: 123.804958,
    contact_number: "(032) 438 9021",
    website: "http://hoyohoy-villas.com/",
    amenities: ["Pool", "Parking", "Breakfast", "Wi-Fi"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "10",
    name: "Blue Ribbon Dive Resort",
    price_per_night: 3105,
    description:
      "Overlooking the bay of Sabang, this relaxed waterfront resort is a 4-minute walk from Sabang Beach and 70 km from Mamburao Airport.",
    address: "National Road",
    city: "Mabini",
    province: "Batangas",
    zip_code: "4202",
    latitude: 13.734684,
    longitude: 120.889449,
    contact_number: "0917 893 2719",
    website: "https://blueribbondivers.com/",
    amenities: ["Pool", "Breakfast", "Wi-Fi", "Parking"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "11",
    name: "Blue Ribbon Dive Resort",
    price_per_night: 2689,
    description:
      "Set along a white-sand beach, this upscale relaxed resort is a 10-minute walk from the shops and restaurants of D'Mall, and 6 km from the tranquil Puka Shell Beach.",
    address: "Beachfront, Station 2 Balabag Boracay Island",
    city: "Boracay",
    province: "Aklan",
    zip_code: "5608",
    latitude: 13.734684,
    longitude: 120.889449,
    contact_number: "0917 893 2719",
    website: "https://blueribbondivers.com/",
    amenities: ["Pool", "Breakfast", "Wi-Fi", "Parking"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "12",
    name: "Henann Regency Resort and Spa",
    price_per_night: 2689,
    description:
      "Set along a white-sand beach, this upscale relaxed resort is a 10-minute walk from the shops and restaurants of D'Mall, and 6 km from the tranquil Puka Shell Beach.",
    address: "Beachfront, Station 2 Balabag Boracay Island",
    city: "Malay",
    province: "Aklan",
    zip_code: "5608",
    latitude: 11.959321,
    longitude: 121.92709,
    contact_number: "(036) 288 6111",
    website: "https://www.henann.com/boracay/henannregency/",
    amenities: ["Pool", "Spa", "Breakfast", "Wi-Fi"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "13",
    name: "Bohol Sunside Resort",
    price_per_night: 1439,
    description:
      "This relaxed hotel in a low-rise building surrounded by trees is 2 km from Alona Beach on the Bohol Sea, 11 km from the limestone Hinagdanan Cave and 18 km from Tagbilaran Airport.",
    address: "Bohol Sunside Resort",
    city: "Panglao",
    province: "Bohol",
    zip_code: "6340",
    latitude: 9.564796,
    longitude: 123.778302,
    contact_number: "(038) 502 4001",
    website: "https://bohol-sunside-resort.com/",
    amenities: ["Pool", "Breakfast", "Wi-Fi", "Parking"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "14",
    name: "Kawili Resort",
    price_per_night: 1098,
    description:
      "Kawili resort is located 500m down the road from the cozy town General Luna. The resort features cottages with horrible WIFI, hot water, AC, relaxing lounging area with swimming pool. The livingroom opens everyday at 8am and serves breakfast, sandwiches and cold drinks.",
    address: "Tourism Rd",
    city: "General Luna",
    province: "Surigao del Norte",
    zip_code: "8419",
    latitude: 9.790992,
    longitude: 126.162347,
    contact_number: "0947 475 9922",
    website: "http://siargaophilippines.com/",
    amenities: ["Pool", "Parking", "Breakfast", "Wi-Fi"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "15",
    name: "Blanco Beach Resort",
    price_per_night: 1098,
    description:
      "Blanco Beach Resort brings you in to a whole new world of what we call, paradise. Blanco Beach Resort makes sure you’ll get the getaway you deserve, a time for you to embrace nature at its finest and rediscover live through relaxation and meditation. We’ll take care of your needs to reach your ultimate venture to explore paradise.",
    address: "Brgy. Logon",
    city: "Daanbantayan Malapascua Island",
    province: "Cebu",
    zip_code: "6013",
    latitude: 11.327871,
    longitude: 124.112997,
    contact_number: "0947 475 9922",
    website: "http://blancobeachresort.com/",
    amenities: ["Breakfast", "Wi-Fi", "Beach access", "Air conditioning"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "16",
    name: "Vista Mar Beach Resort & Country Club",
    price_per_night: 2929,
    description:
      "The resort nestled along the eastern island's line of beaches and locates 15 minutes from Mactan International Airport. It occupies a hectares residential cum leisure development that places Cebu in the roster of world exclusive resort destination.",
    address: "Dapdap",
    city: "Mactan Lapu-Lapu",
    province: "Cebu",
    zip_code: "6015",
    latitude: 10.300143,
    longitude: 124.016386,
    contact_number: "(032) 236 0197",
    website: "http://www.mactanvistamarbeachresort.com/",
    amenities: ["Pool", "Parking", "Breakfast", "Wi-fi"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "17",
    name: "Puerto Del Sol Beach Resort and Hotel Club",
    price_per_night: 3601,
    description:
      "Puerto Del Sol Beach Resort is truly a jewel of the Philippine Isle. Its gleaming pools and airy interiors are artful creations evoking the mysteries of the past along with the serendipitous scent of the present.",
    address: "Patar Rd. Barangay Ilog Malino",
    city: "Bolinao",
    province: "Pangasinan",
    zip_code: "2406",
    latitude: 16.356063,
    longitude: 119.813188,
    contact_number: "(075) 696 0530",
    website: "http://www.puertodelsol.com.ph/",
    amenities: ["Pool", "Breakfast", "Wi-Fi", "Parking"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "18",
    name: "Alta Cebu - resort and convention centre",
    price_per_night: 1412,
    description:
      "This low-key resort, set in gardens beside a river, lies 3 km from scenic beaches and diving at Matcan Reef Flat and 12 km from the 17th-century, Spanish Fort San Pedro.",
    address: "Narra street",
    city: "Cordova",
    province: "Cebu",
    zip_code: "6017",
    latitude: 10.267329,
    longitude: 123.943393,
    contact_number: "(032) 496 7399",
    website: null,
    amenities: ["Pool", "Spa", "Parking", "Breakfast"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "18",
    name: "Alta Cebu - resort and convention centre",
    price_per_night: 1412,
    description:
      "This low-key resort, set in gardens beside a river, lies 3 km from scenic beaches and diving at Matcan Reef Flat and 12 km from the 17th-century, Spanish Fort San Pedro.",
    address: "Narra street",
    city: "Cordova",
    province: "Cebu",
    zip_code: "6017",
    latitude: 10.267329,
    longitude: 123.943393,
    contact_number: "(032) 496 7399",
    website: null,
    amenities: ["Pool", "Spa", "Parking", "Breakfast"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "19",
    name: "Buceo Anilao Beach & Dive Resort",
    price_per_night: 3458,
    description:
      "Across colorful buildings on a lush beachfront property along the Verde Island Passage, this laid-back resort is 8 km from hiking on Mount Panay and 34 km from the Pan–Philippine Highway.",
    address: "Bauan - Mabini Rd",
    city: "Mabini",
    province: "Batangas",
    zip_code: "4202",
    latitude: 13.68655,
    longitude: 120.892174,
    contact_number: "0917 579 7333",
    website: "https://buceoanilao.business.site/",
    amenities: ["Pool", "Beach access", "Spa", "Air conditioning"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },

  {
    _id: "20",
    name: "Dakak Park and Beach Resort",
    price_per_night: 5793,
    description:
      "On a serene beach along the Sulu Sea coast, this relaxed resort is 13 km from Gloria's Fantasyland theme park and 25 km from Dipolog Airport.",
    address: "Barangay Taguilon",
    city: "Dapitan",
    province: "Zamboanga del Norte",
    zip_code: "7101",
    latitude: 8.695339,
    longitude: 123.393373,
    contact_number: "(065) 213 6813",
    website: "http://dakakresort.com/",
    amenities: ["Pool", "Spa", "Parking", "Breakfast"],
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },
];

export default resorts
